[pytest]
testpaths = .
python_files = login.py test_*.py *_test.py *_bdd.py
python_classes = Test*
python_functions = test_*
pythonpath = ..
addopts = --alluredir=report/allure-result --clean-alluredir